# GitHub Action to run cppcheck
# 
name: Cppcheck

on: [push, pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    name: Cppcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install cppcheck
      - name: Cppcheck Core Library
        run: |
          cppcheck --std=c++17 ./asv_sim_gazebo_plugins/include/asv_sim_gazebo_plugins/*.hh
          cppcheck --std=c++17 ./asv_sim_gazebo_plugins/src/*.cc
