name: Ubuntu Jammy CI

on: [push, pull_request]

jobs:
  ubuntu-jammy-ci:
    runs-on: ubuntu-22.04
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: src/asv_sim

      - name: Install Build Essentials
        run: |
          sudo apt-get update && sudo apt-get install \
          wget \
          lsb-release \
          gnupg \
          curl \
          software-properties-common

      - name: Install Build Tools
        run: |
          sudo add-apt-repository universe
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update && sudo apt install -y \
          python3-colcon-common-extensions \
          python3-flake8-docstrings \
          python3-pip \
          python3-pytest-cov \
          python3-vcstool \
          ros-dev-tools

      - name: Install Gazebo Garden
        run: |
          sudo wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
          sudo apt-get update
          sudo apt-get install gz-garden

      - name: Build
        run: |
          colcon build --symlink-install --merge-install --cmake-args \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_CXX_STANDARD=17 \
          -DBUILD_TESTING=ON

      - name: Test
        run: |
          colcon test --merge-install
          colcon test-result --all --verbose
